name: Push docker container to Heroku

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a multi-line script
        run: |
          heroku container:push web -a ddgroleau-api
          heroku container:release web -a ddgroleau-api
