name: Push docker container to Heroku

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Container
        run: heroku container:push web -a ddgroleau-api

      - name: Release Container
        run: heroku container:release web -a ddgroleau-api
